#!/bin/zsh

# Dotfiles/OS
alias yay-install='yay --sync --needed --nodiffmenu --nocleanmenu --noconfirm'
alias yay-update='yay --noconfirm'
alias yay-uninstall='yay -Rsu'
alias yay-ls='pacman -Qei | awk "/^Name/ { name=$3 } /^Groups/ { if ($3 != "base" && $3 != "base-devel") { print name } }"'
alias yay-clean='sudo yay -Rsn $(yay -Qdtq)'
alias yay-aur='yay -Qqm'
alias yay-mirrorlist='sudo reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist'

# Utils
alias server='python -m http.server 8000'
alias weight='du -hs'
touch2() {
  mkdir -p "$(dirname "$1")" && touch "$1"
}
alias empty-trash='trash-empty'

# Node
alias npm='pnpm'
alias npx='pnpm dlx'
alias n='pnpm'
alias touch-package-json='echo "{ \"private\": true }" > package.json'
alias node-cli-boilerplate='curl -fsSL https://github.com/sobrinojulian/node-cli-boilerplate/archive/main.tar.gz | tar -xz --strip-components=1'

# Git/Github
alias onefetch='onefetch --no-palette --show-logo never'
alias of='onefetch'
alias gi='gh issue list'
alias gr='git remote -v'
alias gs='git status'
alias gl='git log'
alias gdiff='git diff -- ":!package-lock.json"'

# npm i *
alias ole='ole | less'
alias boca='aquehorajuegaboca | less'
alias m='mortem 1992/07/07'
alias xtw='xcolor-tailwind'

# better default settings
alias ls='lsd --almost-all --group-dirs=first'
alias cp='cp -iv'
alias mv='mv -iv'
alias md='mkdir -pv'
alias df='df -h'
alias free='free -m'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias cat='bat'

r() {
  redshift -PO $1'500'
}

c() {
  sudo cpupower frequency-set --max $1'MHz'
}

stories() {
  instaloader --login $1 --no-posts --no-profile-pic --no-metadata-json --stories
}

alias pc='pass -c'
